apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.goalService.service.name }}
  labels:
    app: {{ .Values.goalService.name }}
spec:
  type: {{ .Values.goalService.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.goalService.name }}
  ports:
    - name: {{ .Values.goalService.service.portName | default "http" }}
      protocol: {{ .Values.goalService.service.protocol | default "TCP" }}
      port: {{ .Values.goalService.service.port }}
      targetPort: {{ .Values.goalService.service.targetPort }}
