clusterName: nutri-eks-cluster

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::566167302576:role/nutri-eks-cluster-aws-load-balancer-controller-role"

region: eu-central-1

vpcId: "vpc-008d288e2f04776d5"