name: CI/CD Pipeline

on:
  push:
    branches: ["devOps"]
  pull_request:
    branches: ["devOps"]

jobs:
  # backend validation
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd backend/user-service
          npm install 
          cd ../goal-service
          npm install 
          cd ../daily-log-service
          npm install

  # frontend validation
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies & build frontend
        run: |
          cd frontend
          npm install
          npm run build

  # ECR push
  ecr-push:
    needs: ["backend", "frontend"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-frontend:latest
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-frontend:1.0.${{ github.run_number }}

      - name: Push daily-log-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/daily-log-service
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-daily-log-service:latest
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-daily-log-service:1.0.${{ github.run_number }}

      - name: Push goal-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/goal-service
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-goal-service:latest
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-goal-service:1.0.${{ github.run_number }}

      - name: Push user-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/user-service
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-user-service:latest
            ${{ steps.login-ecr.outputs.registry }}/nutri-track-user-service:1.0.${{ github.run_number }}
