name: CI/CD Pipeline

on:
  push:
    branches: ["devOps"]
  pull_request:
    branches: ["devOps"]

jobs:
  # backend validation
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd backend/user-service
          npm install 
          cd ../goal-service
          npm install 
          cd ../daily-log-service
          npm install

  # frontend validation
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies & build frontend
        run: |
          cd frontend
          npm install
          npm run build

  # Docker push

  docker-push:
    needs: ["backend", "frontend"]
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      ECR_REGISTRY: 566167302576.dkr.ecr.eu-central-1.amazonaws.com
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/nutri-track-frontend:latest
            ${{ env.ECR_REGISTRY }}/nutri-track-frontend:${{ github.run_number }}

      - name: push daily-log-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/daily-log-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/nutri-track-daily-log-service:latest
            ${{ env.ECR_REGISTRY }}/nutri-track-daily-log-service:${{ github.run_number }}

      - name: push goal-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/goal-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/nutri-track-goal-service:latest
            ${{ env.ECR_REGISTRY }}/nutri-track-goal-service:${{ github.run_number }}

      - name: push user-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/user-service
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/nutri-track-user-service:latest
            ${{ env.ECR_REGISTRY }}/nutri-track-user-service:${{ github.run_number }}
